---
driver:
  name: docker
driver_config:
  use_sudo: false
  privileged: true

provisioner:
  hosts: localhost
  name: ansible_playbook
  require_chef_for_busser: false
  require_ruby_for_busser: true
  ansible_verbosity: 2
  ansible_verbose: true

platforms:
  - name: ubuntu-16.04
  - name: centos-6
    
# - name: ubuntu-16.04-vagrant
#    driver:
#      name: vagrant
#    driver_config:
#      box: ubuntu/trusty64
#      privileged: true

verifier:
  name: inspec

suites:
  - name: myapp
    run_list:
    attributes:
    #    verifier:
    #      inspec_tests:
    #      - roles/myapp/spec/myapp_spec.rb
    includes:
      - ubuntu-16.04

