<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> 8616b95... Updated dc config for newer version
version: '2.1'

services:
  jenkins:
    #image: 'cloudowski/jenkins:1.1'
    build: ./image/
    hostname: 'jenkins.localhost'
    ports:
      - '8888:8080'
    environment:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"
<<<<<<< HEAD
<<<<<<< HEAD
=======
jenkins:
  #image: 'cloudowski/jenkins:1.1'
  build: ./image/
  #restart: always
  hostname: 'jenkins.localhost'
  ports:
    - '8888:8080'
  environment:
    JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"
>>>>>>> eaa5779... Init with dockerized jenkins
=======
>>>>>>> 8616b95... Updated dc config for newer version
=======
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
>>>>>>> 4219d47... wip
